### ISSUE TITLE
Bug: Moving topic select shows current forum

### ISSUE THREAD

**Issue by BrendaH** [ellmetha/django-machina#133] opened 2018-07-20 10:26 UTC
Testing the 'move topic' interface I encountered a bug.
The select box shows the current forum, though with the obvious intention to have it displayed as a disabled option.

See screenshot (I blacked out some possibly job-sensitive information)
![move topic oops](https://user-images.githubusercontent.com/5462600/42997684-dfd29d5e-8c17-11e8-87b8-ba2a67582ba1.jpg)

I'll be on vacation for the next three weeks and after that I'll have to focus on the permission-system (which is not ideal for my setup), so if anybody else can fix this bug: please go ahead.

**Comment by ellmetha** [comment] 2018-07-21 21:50
Duplicate of #102. I'm closing this one.

**Closed by ellmetha** 2018-07-21 21:50 UTC

**Comment by cmlizama** [comment] 2018-07-24 20:39
I'm still seeing this bug with Django 1.11.3 and django-machina 0.6.0
