### ISSUE TITLE
Duplicated queries

### ISSUE THREAD

**Issue by synw** [ellmetha/django-machina#13] opened 2016-03-14 16:24 UTC
Inspecting a few views using [django-debug-toolbar](https://github.com/django-debug-toolbar/django-debug-toolbar) I have noticed some duplicated queries:

- IndexView: 22 queries including 18 duplicates

- ForumView: 20 queries including 13 duplicates

- TopicView: 13 queries including 3 duplicates

Most of the duplicates seems to come from the app `forum_permission`.

**Comment by ellmetha** [comment] 2016-03-15 17:12
Hi! Are you sure that these queries are really duplicated? These views use many **similar** queries that are performed on each forum involved. But they are not duplicated. ;)

**Comment by synw** [comment] 2016-03-15 18:14
I tested with the master version and it is better: django debug toolbar do not show any duplicated queries on the main views but still sometimes (after posting: 24 queries). I also tried with [django-querycount](https://github.com/bradmontgomery/django-querycount) that shows some duplicates.

Btw even with no duplicates it seems to cost quite a lot in database hits: ex. for TopicView:
Total queries: 17 in 0.4977s

When I post:

"POST /forum/forum/dedez-1/topic/dezdez-1/post/create/ HTTP/1.1" 302 0
Total queries: 26 in 0.9683s

**Comment by ellmetha** [comment] 2016-03-15 18:32
I'm pretty sure that the total queries take less than 0.49s or 0.96s. :) *django-debug-toolbar* does not show queries times above 20ms in my local environment. Can you provide a reproducible way to get such query times?

**Comment by ellmetha** [comment] 2016-03-15 18:33
@synw do you plan to provide a pull request to address this issue?

**Comment by synw** [comment] 2016-03-15 19:03
I don't know man, just telling you what I saw. I tried to check in your code to see if I can help, but it seems too complicated for me. 
In my point of view your app have a good look an feel but looks expensive to run. I would prefer some lightweight / simple and understandable classic Django way solutions for myself, so that it is fast to run and cheap to maintain even if the functionalities are low. I might try to write something.

**Comment by ellmetha** [comment] 2016-03-15 19:15
You should look at the "SQL" tab of the *django-debug-toolbar* and note the time indicated there. Can you tell me if you find such big query times there?

**Comment by synw** [comment] 2016-03-16 18:33
These numbers come from the Sql tab

**Comment by ellmetha** [comment] 2016-03-17 15:16
Ok. I am really surprised to read this because I never observed such query times. That fact that there are 17 or 26 queries on some views is not really important (it's not that much). As I said previously I never observed queries times above 20ms using *django-machina* and many database backends (sqlite, PostgreSQL and MySQL). Moreover it should be noted that *django-machina* has been optimized in order to reduce queries count and duration.

Unless you can provide useful information to reproduce this problem (eg. DB backend, number of forums / topics, etc), I am going to close this issue. ;)

Ah, are you able to observe the problem if you try to use the example projects provided in the repository (https://django-machina.readthedocs.org/en/stable/example_projects.html) ?

**Comment by synw** [comment] 2016-03-18 08:01
The db backend is Postgresql. The server is the dev server. 3 forums with 3 topics each in it.

I tried your example project but I can't make it run because of a problem with django-compressor ( lessc not found ). I don't have time to deal with this. I think your project is good but has reached a level of complexity that make it expensive to maintain. 
Btw 17 or 20 queries is a lot to me: I usually try not to go over 7/8 in my apps.

**Comment by ellmetha** [comment] 2016-03-18 13:58
> The db backend is Postgresql. The server is the dev server. 3 forums with 3 topics each in it.

Ok! I think there is a problem in the configuration of your PostgreSQL server.

> Btw 17 or 20 queries is a lot to me: I usually try not to go over 7/8 in my apps.

It depends on the app you are developing. ;)

I'm closing this issue. If you think that some parts of the project are too complex or need to be simplified / better documented, please open another issue (or better: create a pull request). ;)

**Closed by ellmetha** 2016-03-18 13:58 UTC
